import {
  mdiAccessPointNetwork,
  mdiAirConditioner,
  mdiCarBattery,
  mdiCoffeeMaker,
  mdiCurrentDc,
  mdiDishwasher,
  mdiFan,
  mdiFire,
  mdiFlash,
  mdiFridge,
  mdiGasBurner,
  mdiGate,
  mdiGeneratorPortable,
  mdiKettle,
  mdiLedOn,
  mdiLightbulb,
  mdiLightningBoltCircle,
  mdiMicrowave,
  mdiNas,
  mdiPipeLeak,
  mdiPowerSocketEu,
  mdiPump,
  mdiRouterNetwork,
  mdiRouterWireless,
  mdiServer,
  mdiServerNetwork,
  mdiStove,
  mdiToasterOven,
  mdiTumbleDryer,
  mdiWashingMachine,
  mdiWaterAlert,
  mdiWaterBoiler,
  mdiWaterPump,
} from '@mdi/js'
import type { IconItem, IconPath } from '../../domain/types'

const layer = (path: string, color: string, transform?: string): IconPath => ({ path, color, transform })
const icon = (id: string, label: string, category: string, paths: IconPath[]): IconItem => ({ id, label, category, paths })

export const builtInIcons: IconItem[] = [
  icon('light', 'Освещение', 'Свет', [layer(mdiLightbulb, '#f5b700')]),
  icon('led-on', 'LED-индикатор', 'Свет', [layer(mdiLedOn, '#f5b700')]),
  icon('socket', 'Розетка', 'Электрика', [layer(mdiPowerSocketEu, '#64748b')]),
  icon('battery', 'Аккумуляторная батарея', 'Электрика', [layer(mdiCarBattery, '#22a06b')]),
  icon('boiler', 'Электрокотёл', 'Отопление', [layer(mdiWaterBoiler, '#278b8a'), layer(mdiFlash, '#ffb326', 'translate(12 12) scale(.5)')]),
  icon('gas', 'Газовый котёл', 'Отопление', [layer(mdiWaterBoiler, '#278b8a'), layer(mdiFire, '#f36b45', 'translate(12 12) scale(.5)')]),
  icon('water', 'Бойлер', 'Вода', [layer(mdiWaterBoiler, '#2f83c5')]),
  icon('stove', 'Электроплита / варочная панель', 'Кухня', [layer(mdiStove, '#d15d3d')]),
  icon('oven', 'Духовой шкаф', 'Кухня', [layer(mdiToasterOven, '#6d5d52')]),
  icon('microwave', 'Микроволновая печь', 'Кухня', [layer(mdiMicrowave, '#536e8a')]),
  icon('coffee', 'Кофемашина', 'Кухня', [layer(mdiCoffeeMaker, '#8b5e3c')]),
  icon('kettle', 'Чайник', 'Кухня', [layer(mdiKettle, '#d7921e')]),
  icon('fridge', 'Холодильник', 'Техника', [layer(mdiFridge, '#3186b7')]),
  icon('ac', 'Кондиционер', 'Климат', [layer(mdiAirConditioner, '#3d83c5')]),
  icon('gate', 'Ворота', 'Приводы', [layer(mdiGate, '#746458')]),
  icon('dc', 'Источник постоянного тока', 'Электрика', [layer(mdiCurrentDc, '#4959a7')]),
  icon('rcd', 'Устройство защитного отключения', 'Защита', [layer(mdiLightningBoltCircle, '#f36b45')]),
  icon('washer', 'Стиральная машина', 'Техника', [layer(mdiWashingMachine, '#536e8a')]),
  icon('dryer', 'Сушильная машина', 'Техника', [layer(mdiTumbleDryer, '#b06f3c')]),
  icon('dishwasher', 'Посудомоечная машина', 'Техника', [layer(mdiDishwasher, '#348aa7')]),
  icon('fan', 'Вентиляция', 'Климат', [layer(mdiFan, '#278b8a')]),
  icon('router-wireless', 'Wi-Fi роутер', 'Сеть', [layer(mdiRouterWireless, '#4f75a8')]),
  icon('router-network', 'Сетевой маршрутизатор', 'Сеть', [layer(mdiRouterNetwork, '#37688f')]),
  icon('access-point', 'Точка доступа', 'Сеть', [layer(mdiAccessPointNetwork, '#278b8a')]),
  icon('server', 'Сервер', 'Сеть', [layer(mdiServer, '#657384')]),
  icon('server-network', 'Сетевой сервер', 'Сеть', [layer(mdiServerNetwork, '#4f75a8')]),
  icon('nas', 'Сетевое хранилище NAS', 'Сеть', [layer(mdiNas, '#746458')]),
  icon('generator', 'Генератор', 'Электрика', [layer(mdiGeneratorPortable, '#d7921e')]),
  icon('pump', 'Насос', 'Вода', [layer(mdiPump, '#278b8a')]),
  icon('water-pump', 'Водяная помпа', 'Вода', [layer(mdiWaterPump, '#2f83c5')]),
  icon('pipe-leak', 'Протечка трубы', 'Вода', [layer(mdiPipeLeak, '#2f83c5')]),
  icon('water-alert', 'Датчик протечки', 'Защита', [layer(mdiWaterAlert, '#f36b45')]),
  icon('general', 'Общее', 'Общее', [layer(mdiFlash, '#f5a623')]),
  icon('gas-burner', 'Газовая горелка', 'Отопление', [layer(mdiGasBurner, '#f36b45')]),
]
